/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvRouteImport } from './routes/$inv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvIndexRouteImport } from './routes/$inv/index'
import { Route as InvThemesRouteImport } from './routes/$inv/themes'
import { Route as InvStoriesRouteImport } from './routes/$inv/stories'
import { Route as InvQuotesRouteImport } from './routes/$inv/quotes'
import { Route as InvProfileRouteImport } from './routes/$inv/profile'
import { Route as InvGuestsRouteImport } from './routes/$inv/guests'
import { Route as InvGiftsRouteImport } from './routes/$inv/gifts'
import { Route as InvGalleriesRouteImport } from './routes/$inv/galleries'
import { Route as InvEventsRouteImport } from './routes/$inv/events'

const InvRoute = InvRouteImport.update({
  id: '/$inv',
  path: '/$inv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvIndexRoute = InvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvRoute,
} as any)
const InvThemesRoute = InvThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => InvRoute,
} as any)
const InvStoriesRoute = InvStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => InvRoute,
} as any)
const InvQuotesRoute = InvQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => InvRoute,
} as any)
const InvProfileRoute = InvProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InvRoute,
} as any)
const InvGuestsRoute = InvGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => InvRoute,
} as any)
const InvGiftsRoute = InvGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => InvRoute,
} as any)
const InvGalleriesRoute = InvGalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => InvRoute,
} as any)
const InvEventsRoute = InvEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => InvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$inv': typeof InvRouteWithChildren
  '/$inv/events': typeof InvEventsRoute
  '/$inv/galleries': typeof InvGalleriesRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/guests': typeof InvGuestsRoute
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/quotes': typeof InvQuotesRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv/': typeof InvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$inv/events': typeof InvEventsRoute
  '/$inv/galleries': typeof InvGalleriesRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/guests': typeof InvGuestsRoute
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/quotes': typeof InvQuotesRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv': typeof InvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$inv': typeof InvRouteWithChildren
  '/$inv/events': typeof InvEventsRoute
  '/$inv/galleries': typeof InvGalleriesRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/guests': typeof InvGuestsRoute
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/quotes': typeof InvQuotesRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv/': typeof InvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$inv'
    | '/$inv/events'
    | '/$inv/galleries'
    | '/$inv/gifts'
    | '/$inv/guests'
    | '/$inv/profile'
    | '/$inv/quotes'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$inv/events'
    | '/$inv/galleries'
    | '/$inv/gifts'
    | '/$inv/guests'
    | '/$inv/profile'
    | '/$inv/quotes'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv'
  id:
    | '__root__'
    | '/'
    | '/$inv'
    | '/$inv/events'
    | '/$inv/galleries'
    | '/$inv/gifts'
    | '/$inv/guests'
    | '/$inv/profile'
    | '/$inv/quotes'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvRoute: typeof InvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$inv': {
      id: '/$inv'
      path: '/$inv'
      fullPath: '/$inv'
      preLoaderRoute: typeof InvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$inv/': {
      id: '/$inv/'
      path: '/'
      fullPath: '/$inv/'
      preLoaderRoute: typeof InvIndexRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/themes': {
      id: '/$inv/themes'
      path: '/themes'
      fullPath: '/$inv/themes'
      preLoaderRoute: typeof InvThemesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/stories': {
      id: '/$inv/stories'
      path: '/stories'
      fullPath: '/$inv/stories'
      preLoaderRoute: typeof InvStoriesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/quotes': {
      id: '/$inv/quotes'
      path: '/quotes'
      fullPath: '/$inv/quotes'
      preLoaderRoute: typeof InvQuotesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/profile': {
      id: '/$inv/profile'
      path: '/profile'
      fullPath: '/$inv/profile'
      preLoaderRoute: typeof InvProfileRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/guests': {
      id: '/$inv/guests'
      path: '/guests'
      fullPath: '/$inv/guests'
      preLoaderRoute: typeof InvGuestsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/gifts': {
      id: '/$inv/gifts'
      path: '/gifts'
      fullPath: '/$inv/gifts'
      preLoaderRoute: typeof InvGiftsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/galleries': {
      id: '/$inv/galleries'
      path: '/galleries'
      fullPath: '/$inv/galleries'
      preLoaderRoute: typeof InvGalleriesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/events': {
      id: '/$inv/events'
      path: '/events'
      fullPath: '/$inv/events'
      preLoaderRoute: typeof InvEventsRouteImport
      parentRoute: typeof InvRoute
    }
  }
}

interface InvRouteChildren {
  InvEventsRoute: typeof InvEventsRoute
  InvGalleriesRoute: typeof InvGalleriesRoute
  InvGiftsRoute: typeof InvGiftsRoute
  InvGuestsRoute: typeof InvGuestsRoute
  InvProfileRoute: typeof InvProfileRoute
  InvQuotesRoute: typeof InvQuotesRoute
  InvStoriesRoute: typeof InvStoriesRoute
  InvThemesRoute: typeof InvThemesRoute
  InvIndexRoute: typeof InvIndexRoute
}

const InvRouteChildren: InvRouteChildren = {
  InvEventsRoute: InvEventsRoute,
  InvGalleriesRoute: InvGalleriesRoute,
  InvGiftsRoute: InvGiftsRoute,
  InvGuestsRoute: InvGuestsRoute,
  InvProfileRoute: InvProfileRoute,
  InvQuotesRoute: InvQuotesRoute,
  InvStoriesRoute: InvStoriesRoute,
  InvThemesRoute: InvThemesRoute,
  InvIndexRoute: InvIndexRoute,
}

const InvRouteWithChildren = InvRoute._addFileChildren(InvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvRoute: InvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
