/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvRouteImport } from './routes/$inv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvIndexRouteImport } from './routes/$inv/index'
import { Route as InvWordsRouteImport } from './routes/$inv/words'
import { Route as InvThemesRouteImport } from './routes/$inv/themes'
import { Route as InvStoriesRouteImport } from './routes/$inv/stories'
import { Route as InvProfileRouteImport } from './routes/$inv/profile'
import { Route as InvMediaRouteImport } from './routes/$inv/media'
import { Route as InvGuestsRouteImport } from './routes/$inv/guests'
import { Route as InvGiftsRouteImport } from './routes/$inv/gifts'
import { Route as InvEventsRouteImport } from './routes/$inv/events'
import { Route as InvMediaIndexRouteImport } from './routes/$inv/media/index'
import { Route as InvGuestsIndexRouteImport } from './routes/$inv/guests/index'
import { Route as InvMediaVideoRouteImport } from './routes/$inv/media/video'
import { Route as InvMediaStreamingRouteImport } from './routes/$inv/media/streaming'
import { Route as InvMediaMusicRouteImport } from './routes/$inv/media/music'
import { Route as InvGuestsWishesRouteImport } from './routes/$inv/guests/wishes'

const InvRoute = InvRouteImport.update({
  id: '/$inv',
  path: '/$inv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvIndexRoute = InvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvRoute,
} as any)
const InvWordsRoute = InvWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => InvRoute,
} as any)
const InvThemesRoute = InvThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => InvRoute,
} as any)
const InvStoriesRoute = InvStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => InvRoute,
} as any)
const InvProfileRoute = InvProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InvRoute,
} as any)
const InvMediaRoute = InvMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => InvRoute,
} as any)
const InvGuestsRoute = InvGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => InvRoute,
} as any)
const InvGiftsRoute = InvGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => InvRoute,
} as any)
const InvEventsRoute = InvEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => InvRoute,
} as any)
const InvMediaIndexRoute = InvMediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvMediaRoute,
} as any)
const InvGuestsIndexRoute = InvGuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvGuestsRoute,
} as any)
const InvMediaVideoRoute = InvMediaVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => InvMediaRoute,
} as any)
const InvMediaStreamingRoute = InvMediaStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => InvMediaRoute,
} as any)
const InvMediaMusicRoute = InvMediaMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => InvMediaRoute,
} as any)
const InvGuestsWishesRoute = InvGuestsWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => InvGuestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$inv': typeof InvRouteWithChildren
  '/$inv/events': typeof InvEventsRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/guests': typeof InvGuestsRouteWithChildren
  '/$inv/media': typeof InvMediaRouteWithChildren
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv/words': typeof InvWordsRoute
  '/$inv/': typeof InvIndexRoute
  '/$inv/guests/wishes': typeof InvGuestsWishesRoute
  '/$inv/media/music': typeof InvMediaMusicRoute
  '/$inv/media/streaming': typeof InvMediaStreamingRoute
  '/$inv/media/video': typeof InvMediaVideoRoute
  '/$inv/guests/': typeof InvGuestsIndexRoute
  '/$inv/media/': typeof InvMediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$inv/events': typeof InvEventsRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv/words': typeof InvWordsRoute
  '/$inv': typeof InvIndexRoute
  '/$inv/guests/wishes': typeof InvGuestsWishesRoute
  '/$inv/media/music': typeof InvMediaMusicRoute
  '/$inv/media/streaming': typeof InvMediaStreamingRoute
  '/$inv/media/video': typeof InvMediaVideoRoute
  '/$inv/guests': typeof InvGuestsIndexRoute
  '/$inv/media': typeof InvMediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$inv': typeof InvRouteWithChildren
  '/$inv/events': typeof InvEventsRoute
  '/$inv/gifts': typeof InvGiftsRoute
  '/$inv/guests': typeof InvGuestsRouteWithChildren
  '/$inv/media': typeof InvMediaRouteWithChildren
  '/$inv/profile': typeof InvProfileRoute
  '/$inv/stories': typeof InvStoriesRoute
  '/$inv/themes': typeof InvThemesRoute
  '/$inv/words': typeof InvWordsRoute
  '/$inv/': typeof InvIndexRoute
  '/$inv/guests/wishes': typeof InvGuestsWishesRoute
  '/$inv/media/music': typeof InvMediaMusicRoute
  '/$inv/media/streaming': typeof InvMediaStreamingRoute
  '/$inv/media/video': typeof InvMediaVideoRoute
  '/$inv/guests/': typeof InvGuestsIndexRoute
  '/$inv/media/': typeof InvMediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$inv'
    | '/$inv/events'
    | '/$inv/gifts'
    | '/$inv/guests'
    | '/$inv/media'
    | '/$inv/profile'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv/words'
    | '/$inv/'
    | '/$inv/guests/wishes'
    | '/$inv/media/music'
    | '/$inv/media/streaming'
    | '/$inv/media/video'
    | '/$inv/guests/'
    | '/$inv/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$inv/events'
    | '/$inv/gifts'
    | '/$inv/profile'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv/words'
    | '/$inv'
    | '/$inv/guests/wishes'
    | '/$inv/media/music'
    | '/$inv/media/streaming'
    | '/$inv/media/video'
    | '/$inv/guests'
    | '/$inv/media'
  id:
    | '__root__'
    | '/'
    | '/$inv'
    | '/$inv/events'
    | '/$inv/gifts'
    | '/$inv/guests'
    | '/$inv/media'
    | '/$inv/profile'
    | '/$inv/stories'
    | '/$inv/themes'
    | '/$inv/words'
    | '/$inv/'
    | '/$inv/guests/wishes'
    | '/$inv/media/music'
    | '/$inv/media/streaming'
    | '/$inv/media/video'
    | '/$inv/guests/'
    | '/$inv/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvRoute: typeof InvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$inv': {
      id: '/$inv'
      path: '/$inv'
      fullPath: '/$inv'
      preLoaderRoute: typeof InvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$inv/': {
      id: '/$inv/'
      path: '/'
      fullPath: '/$inv/'
      preLoaderRoute: typeof InvIndexRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/words': {
      id: '/$inv/words'
      path: '/words'
      fullPath: '/$inv/words'
      preLoaderRoute: typeof InvWordsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/themes': {
      id: '/$inv/themes'
      path: '/themes'
      fullPath: '/$inv/themes'
      preLoaderRoute: typeof InvThemesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/stories': {
      id: '/$inv/stories'
      path: '/stories'
      fullPath: '/$inv/stories'
      preLoaderRoute: typeof InvStoriesRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/profile': {
      id: '/$inv/profile'
      path: '/profile'
      fullPath: '/$inv/profile'
      preLoaderRoute: typeof InvProfileRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/media': {
      id: '/$inv/media'
      path: '/media'
      fullPath: '/$inv/media'
      preLoaderRoute: typeof InvMediaRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/guests': {
      id: '/$inv/guests'
      path: '/guests'
      fullPath: '/$inv/guests'
      preLoaderRoute: typeof InvGuestsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/gifts': {
      id: '/$inv/gifts'
      path: '/gifts'
      fullPath: '/$inv/gifts'
      preLoaderRoute: typeof InvGiftsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/events': {
      id: '/$inv/events'
      path: '/events'
      fullPath: '/$inv/events'
      preLoaderRoute: typeof InvEventsRouteImport
      parentRoute: typeof InvRoute
    }
    '/$inv/media/': {
      id: '/$inv/media/'
      path: '/'
      fullPath: '/$inv/media/'
      preLoaderRoute: typeof InvMediaIndexRouteImport
      parentRoute: typeof InvMediaRoute
    }
    '/$inv/guests/': {
      id: '/$inv/guests/'
      path: '/'
      fullPath: '/$inv/guests/'
      preLoaderRoute: typeof InvGuestsIndexRouteImport
      parentRoute: typeof InvGuestsRoute
    }
    '/$inv/media/video': {
      id: '/$inv/media/video'
      path: '/video'
      fullPath: '/$inv/media/video'
      preLoaderRoute: typeof InvMediaVideoRouteImport
      parentRoute: typeof InvMediaRoute
    }
    '/$inv/media/streaming': {
      id: '/$inv/media/streaming'
      path: '/streaming'
      fullPath: '/$inv/media/streaming'
      preLoaderRoute: typeof InvMediaStreamingRouteImport
      parentRoute: typeof InvMediaRoute
    }
    '/$inv/media/music': {
      id: '/$inv/media/music'
      path: '/music'
      fullPath: '/$inv/media/music'
      preLoaderRoute: typeof InvMediaMusicRouteImport
      parentRoute: typeof InvMediaRoute
    }
    '/$inv/guests/wishes': {
      id: '/$inv/guests/wishes'
      path: '/wishes'
      fullPath: '/$inv/guests/wishes'
      preLoaderRoute: typeof InvGuestsWishesRouteImport
      parentRoute: typeof InvGuestsRoute
    }
  }
}

interface InvGuestsRouteChildren {
  InvGuestsWishesRoute: typeof InvGuestsWishesRoute
  InvGuestsIndexRoute: typeof InvGuestsIndexRoute
}

const InvGuestsRouteChildren: InvGuestsRouteChildren = {
  InvGuestsWishesRoute: InvGuestsWishesRoute,
  InvGuestsIndexRoute: InvGuestsIndexRoute,
}

const InvGuestsRouteWithChildren = InvGuestsRoute._addFileChildren(
  InvGuestsRouteChildren,
)

interface InvMediaRouteChildren {
  InvMediaMusicRoute: typeof InvMediaMusicRoute
  InvMediaStreamingRoute: typeof InvMediaStreamingRoute
  InvMediaVideoRoute: typeof InvMediaVideoRoute
  InvMediaIndexRoute: typeof InvMediaIndexRoute
}

const InvMediaRouteChildren: InvMediaRouteChildren = {
  InvMediaMusicRoute: InvMediaMusicRoute,
  InvMediaStreamingRoute: InvMediaStreamingRoute,
  InvMediaVideoRoute: InvMediaVideoRoute,
  InvMediaIndexRoute: InvMediaIndexRoute,
}

const InvMediaRouteWithChildren = InvMediaRoute._addFileChildren(
  InvMediaRouteChildren,
)

interface InvRouteChildren {
  InvEventsRoute: typeof InvEventsRoute
  InvGiftsRoute: typeof InvGiftsRoute
  InvGuestsRoute: typeof InvGuestsRouteWithChildren
  InvMediaRoute: typeof InvMediaRouteWithChildren
  InvProfileRoute: typeof InvProfileRoute
  InvStoriesRoute: typeof InvStoriesRoute
  InvThemesRoute: typeof InvThemesRoute
  InvWordsRoute: typeof InvWordsRoute
  InvIndexRoute: typeof InvIndexRoute
}

const InvRouteChildren: InvRouteChildren = {
  InvEventsRoute: InvEventsRoute,
  InvGiftsRoute: InvGiftsRoute,
  InvGuestsRoute: InvGuestsRouteWithChildren,
  InvMediaRoute: InvMediaRouteWithChildren,
  InvProfileRoute: InvProfileRoute,
  InvStoriesRoute: InvStoriesRoute,
  InvThemesRoute: InvThemesRoute,
  InvWordsRoute: InvWordsRoute,
  InvIndexRoute: InvIndexRoute,
}

const InvRouteWithChildren = InvRoute._addFileChildren(InvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvRoute: InvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
